### ISSUE TITLE
Clean up code/design ('Hello world')

### ISSUE THREAD

**Issue by lukefretwell** [cagov/Alpha#11]

**Comment by lukefretwell** [comment]
[Alpha.zip](https://github.com/cagov/Alpha/files/3919096/Alpha.zip)

@artuoma attached are the files.

**Comment by lukefretwell** [comment]
@artuoma updated version that changes #212121 to #000000.
[Alpha.zip](https://github.com/cagov/Alpha/files/3923290/Alpha.zip)

**Comment by lukefretwell** [comment]
- [ ] Remove the commented code that's not being used.
- [ ] Alphabar should be #000000. OK for the official bar to be like it is in the comp (or just make it #000000).
- [ ] The state in between the 'Hello' and 'California' isn't working on mobile, but we should really keep it above and not insert images in between structured mark-up.
- [ ] Remove the <br> space between paragraphs and 'Team Alpha.CA.gov.' If we feel like there needs to be more paragraph space, add it to the CSS.

**Comment by artuoma** [comment]
This is complete

**Comment by lukefretwell** [comment]
@artuoma alphabar should be #000000.

**Comment by lukefretwell** [comment]
Folding this into https://github.com/cagov/Alpha/issues/10
