### ISSUE TITLE
'Digital Government Performance' status bar

### ISSUE THREAD

**Issue by lukefretwell** [cagov/Alpha#12]
As a user, I'd like to see a status bar of key digital performance indicators, so I can see how CA.gov is meeting this criteria.

Initial indicators:

*  HTTPS
* Accessibility
* Page load

Would also be great to have a /performance page that explains what each of these are.

cc @artuoma @aaronhans @abquirarte

**Comment by lukefretwell** [comment]
Example:

![FireShot Capture 123 - CA gov - State of California - ](https://user-images.githubusercontent.com/1569463/70207578-0c1e0200-16e0-11ea-8a3d-3e47d532228b.png)

**Comment by abquirarte** [comment]
Loving this!

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by artuoma** [comment]
Would this be a good place to ask the user if the particular page is useful?  
![image](https://user-images.githubusercontent.com/20782462/70688775-616d8c80-1c67-11ea-8b84-15195d882f47.png)
