### ISSUE TITLE
Settings page/function

### ISSUE THREAD

**Issue by lukefretwell** [cagov/Alpha#168]
Would love to get insights into setting up an MVP /settings page so that we can start thinking about the individual user and how they can customize the site based on their particular needs. I want us to start thinking in this way rather than the traditional one interface (+ put a blue on it) approach. Having basic settings will help us all be more insightful into how we think about product inclusion.

Two MVP features to this page:

* light (default) + dark mode
* font selector (default + dyslexic a la https://gumroad.com/l/OpenDyslexic)

cc @artuoma @aaronhans

**Comment by lukefretwell** [comment]
There doesn't appear to be any significant added value to OpenDyslexic or other related fonts:

* https://eyeondesign.aiga.org/can-fonts-really-help-those-with-dyslexia/
* https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5629233/
* http://dyslexiahelp.umich.edu/sites/default/files/good_fonts_for_dyslexia_study.pdf
* https://www.understood.org/en/learning-thinking-differences/child-learning-disabilities/dyslexia/dyslexia-friendly-font

Does this research negates the need to do add this?

**Comment by abquirarte** [comment]
love that you are thinking about product inclusion. What other functions should we be thinking about?
