### ISSUE TITLE
Determine content types

### ISSUE THREAD

**Issue by abquirarte** [cagov/Alpha#19]
- [ ] quick answer

- [ ] step by step

- [ ] smart answer (calculator)

- [ ] transaction start page

- [ ] guide

- [ ] location search

- [ ] news 

Descriptions and Content Type Examples from PD: https://drive.google.com/a/alpha.ca.gov/file/d/1CmyDVKfkJ9FhAgx-lUFZ6HUqltrAFeQD/view?usp=sharing 

Gov.UK: https://design-system.service.gov.uk/components/

**Comment by lukefretwell** [comment]
- [ ] Finalize content types

- [ ] Design templates for each (incorporate into CWDS)

- [ ] Reference in handbook in content section

**Comment by abquirarte** [comment]
Can we also connect how these connect to #38 and #21 ?
