### ISSUE TITLE
What is the best way for us to make sure static assets are compressed in azure

### ISSUE THREAD

**Issue by aaronhans** [cagov/Alpha#20]
Could we check in with other teams or do our own research and come up with a deployment process we should follow that will make sure our static assets are compressed (gzipped or brotli'd) when delivered to end users.

We can put them in blog storage or pre compress as part of the build process and deliver directly from our server, I don't have an opinion on the best way to accomplish this, we can use whatever process is easiest in our azure environment

**Comment by carterm** [comment]
With our current Azure environment, all text content appears to have the encoding type "gzip."  We may already be good to go here, but we should periodically check to make sure all our text content types are gzipped.  Recommend close.

**Comment by ChadABratton** [comment]
We can close this, Carter and Aaron confirmed this issue is no longer accurate.

**Comment by abquirarte** [comment]
Thank you!
