### ISSUE TITLE
Release 1 Bug Reports and Fixes

### ISSUE THREAD

**Issue by abquirarte** [cagov/Alpha#200]
See working document:  
https://docs.google.com/spreadsheets/d/1VWjVzloaH6XE3dmgbpGbEtjpQtWY72wriVJMlNCHKmo/edit#gid=0

### Bug List:

- [x] Espanol vs Spanish in banner
- [x] Min Wage page left over code
- [x] All links should open in the same window, Hyperlinks don't consistently open up (new window vs. same window) 
- [x] Independence day cut-off (Eng page, mobile view)
- [x] Add News link to blog
- [x] Fix responsive design on Min Wage, State Holidays, Contractor pages
- [x] Fix map for mobile view on for banks
- [x] Change to Espanol in language (vs Spanish)
- [x]  Fix the feedback form on the embed...  
![image](https://user-images.githubusercontent.com/9556188/72399422-fcd89e00-36fa-11ea-9bdd-ef6416b67b25.png)
See [Luke's comment](https://github.com/cagov/Alpha/issues/200#issuecomment-574472935) on fix below. 
- [x] Food banks mobile search does not work
- [x] Food banks on mobile (chrome) takes me to the test site. 
![image](https://user-images.githubusercontent.com/9556188/72400921-7f635c80-36ff-11ea-9098-e23d1a311476.png)
- [x] First accordion on minimum wage doesn't open after opening --> closing then trying to open again (https://alpha.ca.gov/services/find-minimum-wage-your-city/)
- [x] Second accordion on minimum wage doesn't open on mobile (https://alpha.ca.gov/services/find-minimum-wage-your-city/)

### TEST Site: 
https://staging.alpha.technology.ca.gov/

**Comment by lukefretwell** [comment]
@abquirarte @carterm @aaronhans @artuoma looks like the `.smcx-embed` class is 650px when it should be 1100px. Works when I change it to 1100px.

<img width="1239" alt="Screen Shot 2020-01-14 at 6 56 23 PM" src="https://user-images.githubusercontent.com/1569463/72400978-a883ed00-36ff-11ea-94af-5e70f76be43a.png">

**Comment by carterm** [comment]
Fixed in staging. 
https://staging.alpha.technology.ca.gov/feedback/

**Comment by aaronhans** [comment]
We deprioritized this piece and will address in a new issue: - [ ] Fix Accordion A11y
