### ISSUE TITLE
Site search

### ISSUE THREAD

**Issue by lukefretwell** [cagov/Alpha#201]
**Is your feature request related to a problem? Please describe.**
As a visitor to CA.gov, I'd like to be able to search for available services and information,.

**Describe the solution you'd like**
Sitewide search box accessible from every page on CA.gov.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by abquirarte** [comment]
Source: https://twitter.com/MoKenneyney/status/1216924212872376320

**Comment by ChaseKR** [comment]
Yeah, wasn't this part of the plan originally? I guess I misunderstood. It's so easy to set up these days with Elasticsearch and whatnot . Happy to help!

**Comment by abquirarte** [comment]
thank you @ChaseKR !

**Comment by ChaseKR** [comment]
Thank you! I love the work y'all are doing 😊
