### ISSUE TITLE
Create UX issue template

### ISSUE THREAD

**Issue by lukefretwell** [cagov/Alpha#202]
- [x] Create design issue checklist
- [x] Link to sample template (https://github.com/cagov/UX/issues/59)

**Comment by lukefretwell** [comment]
@artuoma moving this to backlog until we refine prototyping discussion.

**Comment by lukefretwell** [comment]
@artuoma comments:

* add check for wireframe (if needed)
* something about making sure I get at least a once-over pass (☯️)
* Make this a list in the template? (Manual accessibility checks performed (See checklist: https://drive.google.com/open?id=0B72FqFUONAggazJwQURQeTBPMEZGRjJXSFNGcDJrMF9ENERR))

**Comment by artuoma** [comment]
Take a look: https://github.com/cagov/UX/blob/master/.github/ISSUE_TEMPLATE/UX-issue

**Comment by lukefretwell** [comment]
@artuoma that links doesn't work for me. Did you see my comments? I don't see them incorporated when I attempt to create a new issue.

**Comment by abquirarte** [comment]
https://github.com/cagov/UX/issues/new/choose

**Comment by abquirarte** [comment]
@lukefretwell ☝️
