### ISSUE TITLE
Caltrans: will our ideas work? (API, data match up)

### ISSUE THREAD

**Issue by aaronhans** [cagov/Alpha#227]
Make sure we can match up data returned by directions API to data returned by Caltrans road conditions endpoints

**Comment by abquirarte** [comment]
Does this require you meeting with them? Should we try to connect with them today? 

cc: @KimberlyglennTSM

**Comment by aaronhans** [comment]
No this is just an issue for me to work on code. Sorry that wasn't clear

**Comment by aaronhans** [comment]
Was able to create a working prototype that:
- translates direction steps from mapbox to caltrans route names
- retrieves all caltrans lane closure data and reorganizes it in format that is easier to query across districts
- can display incident data per highway inside bounding box of trip

**Comment by abquirarte** [comment]
Aaron sent follow-up questions to Kimberly. Should continue tracking in the respective Github issue. Or at least point back to the main story: https://github.com/cagov/UX/issues/37
