### ISSUE TITLE
Project validation for header hierarchy.

### ISSUE THREAD

**Issue by carterm** [cagov/Alpha#229]
Ensure that any pull requests that contain HTML pages have a proper header hierarchy.

H1->H2->H3

- [x] Implement Change
- [x] Create review

**Comment by carterm** [comment]
Implemented.  Check out this [Pull Request](https://github.com/cagov/Alpha/pull/234) to see how it fails validation if I enter a H tag out of order.

**Comment by carterm** [comment]
Even better, look at this [commit](https://github.com/cagov/Alpha/pull/234/commits/112d744da524b2eeca0c3d82116e7dba46a195b0) that has the validation error next to it.

**Comment by abquirarte** [comment]
✅
