### ISSUE TITLE
Flag image issue in 'official' band

### ISSUE THREAD

**Issue by lukefretwell** [cagov/Alpha#238]
**Describe the bug**
via @hilaryhb: "I’m getting weird overlap w official and the logo are image iPhone chrome"

**Screenshots**

![File](https://user-images.githubusercontent.com/1569463/72832619-14071680-3c3a-11ea-97a0-adb944f3fd93.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by artuoma** [comment]
https://github.com/cagov/UX/commit/9356f51774d3977acedb246a97ce4e5d77e76196

Updated the official header to resolve the issue.

**Comment by abquirarte** [comment]
Thanks @artuoma
