### ISSUE TITLE
Tokenized language support

### ISSUE THREAD

**Issue by carterm** [cagov/Alpha#246]
In order to reduce complexity for multi-language support, we should have tokens for embedded language that can be replaced with translations.

Currently we have separate files for each language.

**Comment by carterm** [comment]
Webpack improvements in prep - https://github.com/cagov/Alpha/pull/245

**Comment by carterm** [comment]
Created a separate issue to get help with the language matrix...
https://github.com/cagov/Alpha/issues/258

**Comment by carterm** [comment]
When do we close these?

**Comment by abquirarte** [comment]
This is ongoing for new pages, perhaps we track the tokenizing in one of the template issues. (Main Story, Prototype, Translation)
