### ISSUE TITLE
Map embed causing scroll issues

### ISSUE THREAD

**Issue by lukefretwell** [cagov/Alpha#247]
**Describe the bug**
When scrolling on food banks page, the map maximizes and then disables scrolling.

My suggestion would be to remove the embed and think about how we can better display this type of function.

**To Reproduce**
1. Go to https://alpha.ca.gov/services/find-food-banks-near-you/
2. Scroll down to and over the map.

**Screenshots**

![Jan-22-2020 16-59-55](https://user-images.githubusercontent.com/1569463/72948105-097f7680-3d39-11ea-966f-d341d451a544.gif)

cc @artuoma @humancenteredhuman @aaronhans

**Comment by aaronhans** [comment]
We could just remove the map on mobile or touchscreens or we could implement one of the disable one touch zoom methods people are using here: https://github.com/mapbox/mapbox-gl-js/issues/2618

the code listed in those issues attempts to recreate the google maps behavior on mobile where you can't interact with the map with a single finger scroll which prevents accidental movement

**Comment by lukefretwell** [comment]
@aaronhans the screenshot is from the desktop experience. The suggestion you have is better but still doesn't solve the problem of scrolling beyond the map. Instead of zooming, you're just panning down the map. Or am I missing something?

**Comment by aaronhans** [comment]
<img width="755" alt="Screen Shot 2020-02-02 at 6 20 02 PM" src="https://user-images.githubusercontent.com/353360/73620924-dbc3e880-45e8-11ea-9848-65646f1301c5.png">

Addressed the issue by blocking scroll wheel or single finger zoom by default and showing the user a message telling them how to intentionally interact

**Comment by aaronhans** [comment]
commit: https://github.com/cagov/Alpha/commit/5d8797df565b8fd78822755c17512e6f7a2a929c

**Comment by lukefretwell** [comment]
@aaronhans I'm still experiencing the same issue as initially reported.

**Comment by aaronhans** [comment]
Sorry, we only have the fix in staging at this point. I see improved behavior at this url for scroll wheel behavior in desktop chrome and for finger scroll on ipad https://staging.alpha.technology.ca.gov/services/find-food-banks-near-you/
