### ISSUE TITLE
Search: This would have to come at the end when we have more content, but think we should have something related to this.

### ISSUE THREAD

**Issue by abquirarte** [cagov/Alpha#248]
** @lukefretwell suggestion** 

_Search: This would have to come at the end when we have more content, but think we should have something related to this._

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lukefretwell** [comment]
Closing this as it's a dupe of https://github.com/cagov/Alpha/issues/201.
