### ISSUE TITLE
add more food banks

### ISSUE THREAD

**Issue by aaronhans** [cagov/Alpha#254]
**Describe the bug**
Missing many known food banks

**To Reproduce**
Searching for San Francisco returns only east bay results

**Expected behavior**
Retrieve SF food bank data and add it to this app

**Additional context**
We can also augment the data from many other areas using resources identified in https://docs.google.com/document/d/1K_ZyTi2Jhs77zlKhBoCUukJdoJuhHrppiG0x1wUBCiw/edit#heading=h.gjdgxs 

We should also remove the json from the Alpha repo and create an API with the data

**Comment by abquirarte** [comment]
Thank you again @tdooner for flagging. 😄 If you know better data sources, we'd love to know where to look.

**Comment by abquirarte** [comment]
Also we should look into the logic for the text message. Do we need to change our messaging on this if data is not available in the location? CC: @humancenteredhuman @aaronhans @KimberlyglennTSM 

Fix case sensitive. 

My experience on personal phone captured below:
![123_1(3)](https://user-images.githubusercontent.com/9556188/73224167-78841300-411d-11ea-8062-270e787886ec.jpeg)
![123_1(1)](https://user-images.githubusercontent.com/9556188/73224168-78841300-411d-11ea-96dc-444466b79c48.jpeg)

**Comment by aaronhans** [comment]
Missing food bank @carterm is at right now:

Sacramento Food Bank & Family Services
1951 Bell Ave, Sacramento, CA 95838
(916) 925-3240
https://goo.gl/maps/vPNNhq5RU4fqUfRw9

**Comment by aaronhans** [comment]
- [ ] added 160 new food bank/pantry locations from the foodoasis.la dataset
- [ ] troubleshoot the SMS failures
- [ ] update the food banks page in Alpha to use the new api

**Comment by aaronhans** [comment]
I fixed the case sensitivity, updated the food bank dataset in the SMS app to use the fully scraped dataset we uploaded to our new API and added more string match error catching. Seems to be working properly for me now but I wasn't able to repro the issues before. Let's test the SMS again a few times on Angie's phones

**Comment by abquirarte** [comment]
Let's test away!
Thank you aaron

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
