### ISSUE TITLE
where are the flipping unit tests on the web components?

### ISSUE THREAD

**Issue by aaronhans** [cagov/Alpha#255]
I see a couple cool web components but no unit tests on them, need to add unit tests in the open-wc style

**Comment by aaronhans** [comment]
- [ ] use karma style unit testing approach from open-wc
- [ ] write at least one valid unit test
- [ ] publish module to npm
- [ ] update the UX repo to pull js from published modules

**Comment by abquirarte** [comment]
✅ closing
