### ISSUE TITLE
build minimum wage page

### ISSUE THREAD

**Issue by aaronhans** [cagov/Alpha#26]
https://cagov.github.io/exp/mw/index.html

**Comment by aaronhans** [comment]
Built 2 versions of this based on google docs created by Rebecca. These initial versions are hosted on the user testing repository.

I deployed these to a different repository because I wanted to do fast prototyping outside of the production deployment pipeline. Doing this allows us to play with several versions many of which will definitely be thrown away, then when we gathered user testing responses we'd rebuild our best version as part of the alpha.ca.gov site repository where it will go through staging and all the final review checks listed here: https://docs.google.com/document/d/1rHhMA0xwmNlc94xgIN_n9mYqifWq8JHCBiArnL3kE1U/edit#heading=h.y92zfbhz5ph0 and we can continue to iterate on this refined version as part of the alpha.ca.gov site

**Comment by aaronhans** [comment]
New urls now in updated repo:
v1: https://cagov.github.io/UX/mw/  
v2: https://cagov.github.io/UX/mw/v2.html  
data exploration: https://cagov.github.io/UX/map/

**Comment by aaronhans** [comment]
Updates from Luke:

Can we use this page template: https://cagov.github.io/cwds/service.html
Is there an issue we can add comments to? Slack really buries the string.
@Artem Khomishen to your comment on building design system/components based on working content types, would be great to update the accordion and button and incorporate into CWDS (@Aaron Hans not sure what I did, but it's displaying the way I intented to here: https://cagov.github.io/cwds/index.html)
Would add 'Exceptions' h2 above accordion.
Would put 'Learn more ...' below accordion, but simplify to a format like 'Details: #link to page#'
cagov.github.io
CA.gov - State of California
The official website for the State of California.
cagov.github.io
CA.gov - State of California
The official website for the State of California.


Luke Fretwell:black_medium_square:  7 minutes ago
Also re::point_up:, if we doing comps in Google Docs, then we should include the results display and use the page headings to denote what's an h3, etc.

Luke Fretwell:black_medium_square:  6 minutes ago
And I would put a colon after a CTA before a field. So 'Please enter your city:' The 'Please' is a little additive to me.

**Comment by aaronhans** [comment]
new version: https://cagov.github.io/UX/mw/v3.html @lukefretwell

**Comment by lukefretwell** [comment]
Very nice @aaronhans!

Feedback:

- [ ] Form field is small on phone
- [ ] Header fonts aren't same as CWDS (bold)
- [ ] Accordions aren't dropping down (@artuoma we should display: block the links on these)
- [ ] Having the same CTA for the header and the button seems redundant. Seems like we should keep the buttons simple with a few standard options (Search, Go, Next, etc.)
- [ ] Delete period after DIR
- [ ] Should 'Exceptions' be `<h2>` ?
- [ ] Something about the search result doesn't stand out. I'm not sure if it's because it's below the search box and I have to know to scroll down (on phone) or if it should be formatted in a more structured way with less text like:

## Malibu (CA) minimum wage

| Employers with 25 or fewer employees      | Employers with 26 or more employees |
| ----------- | ----------- |
| $14.25/hour   | $15/hour        |

cc @humancenteredhuman

**Comment by aaronhans** [comment]
I am working on a v4, letting @humancenteredhuman own copy, she is already committing changes to text and HTML via git

todo:
- review form field size on phone
- fix header/body alignment to match new template
- the accordion hit area is only the text but should be the whole bar. Will address this https://github.com/cagov/cwds/issues/3
- review, fix font sizes to match design
- scrolling the page down slightly after you hit the button to see wage makes sense especially on mobile, will create a new version with that addition
- hide all the exception info and the more info link until after you see a wage result

**Comment by aaronhans** [comment]
fixed:
- added full list of CA cities to autocomplete
- added full list of zip codes for autocomplete
- added logic to resolve zip codes to multiple cities when appropriate
- fixed some aria issues

new todo:
- create version with plain dropdown instead of custom autocomplete (requested by @humancenteredhuman , seems like great idea)

**Comment by KimberlyglennTSM** [comment]
reviewed and approved changes.
