### ISSUE TITLE
Run strings on Disability Insurance through Azure Translator

### ISSUE THREAD

**Issue by abquirarte** [cagov/Alpha#260]
We want to translate: https://cagov.github.io/UX/disability-insurance/

Need to know the new process to translate 

API, then map to matrix, then validate?

**Comment by abquirarte** [comment]
@aaronhans (did I make sense? lol)

**Comment by aaronhans** [comment]
Yep

**Comment by aaronhans** [comment]
This is now obsolete, the =GOOGLETRANSLATE function in sheets is superior to the Azure translation API

**Comment by abquirarte** [comment]
Thanks, that's what I thought!
