### ISSUE TITLE
Integrate CalGrant from UX to Alpha

### ISSUE THREAD

**Issue by carterm** [cagov/Alpha#284]
Integrate CalGrant from UX to Alpha

**Comment by carterm** [comment]
UX page [here](https://cagov.github.io/UX/cal-grant/)

**Comment by abquirarte** [comment]
closing! :)

**Comment by carterm** [comment]
Not done yet...still have to put the steps in.

**Comment by carterm** [comment]
All UX pages to be moved...
https://cagov.github.io/UX/cal-grant/
https://cagov.github.io/UX/cal-grant/step-1.html
https://cagov.github.io/UX/cal-grant/step-2.html
https://cagov.github.io/UX/cal-grant/finish.html

**Comment by carterm** [comment]
Now it's done.  In staging [here](https://staging.alpha.technology.ca.gov/apply-for-cal-grant/).

**Comment by carterm** [comment]
Done.  Deployed to staging
https://staging.alpha.technology.ca.gov/apply-for-cal-grant/
