### ISSUE TITLE
www redirect issue

### ISSUE THREAD

**Issue by ChadABratton** [cagov/Alpha#298]
Alpha.ca.gov is not redirecting properly. 
We currently have two versions of each page, one with www. and one without www.

- [x] create listeners, rules, https settings, and health probes for www redirect
- [x] Test if redirects from non www to www are working as intended
- [x] remove redirect configurations
- [x] re-add redirects and test to ensure we are confident with changes. 
- [x] make new github issue to apply to prod

**Comment by ChadABratton** [comment]
After testing today, we still cannot determine what is causing this issue. Also had CDT team check, we went through 4 different sites in Azure that are working properly and we still have not been able to apply the correct redirects to the alpha site. More testing is happening tonight.

**Comment by ChadABratton** [comment]
CDN cacheing was causing the testing issues and bad data.  We need to purge each page after a release and then we can test properly. 
Update: After purging, www redirects are working properly for [test prod](https://www.testprod.alpha.technology.ca.gov/)

Plan:
Before applying www redirect to production, we are going to test the process again to be sure we can replicate all changes smoothly. I will remove the www redirect from test prod and re-apply the redirect rules to ensure we are confident with the changes before moving to production alpha.ca.gov

**Comment by ChadABratton** [comment]
All done! successfully applied all settings to test prod. 
https://docs.google.com/document/d/1YY5axKhi6r0_7fPJUXu6iw5BPSIOxmHR/edit

**Comment by abquirarte** [comment]
Thank you so much @ChadABratton ! ✅ 👏
