### ISSUE TITLE
End to End testing for foodbanks

### ISSUE THREAD

**Issue by ChadABratton** [cagov/Alpha#302]
At a minimum, the foodbanks page must autocomplete and display results near you.

- [x] Auto complete test (autofill of zip codes)
- [x] results near you returns all results (test for # of returned results to be greater than 0)

**Comment by ChadABratton** [comment]
Foodbanks - auto complete test is written and working, here is the code:
`describe("food banks", () => {
  test("fb autocomplete works", async () => {
    await page.goto(hostname+'/services/find-food-banks-near-you/');
    await page.waitForSelector(".city-search");
    await page.type(".city-search", '9582');

    await page.waitForSelector("#awesomplete_list_1 li");
    let listitems = await page.$$eval('#awesomplete_list_1 li', listitems => { return listitems });
    expect(listitems.length).toBeGreaterThan(1);

  }, 16000);
});`

**Comment by ChadABratton** [comment]
2nd test complete! 
![image](https://user-images.githubusercontent.com/28573666/73891865-16689380-482a-11ea-8b0c-c329d562ea7f.png)


Code checked into master branch!
https://github.com/cagov/Alpha/commit/1b52dfe2fec69c25bdc663eb3368cb7f9b62c215

![image](https://user-images.githubusercontent.com/28573666/73891904-36985280-482a-11ea-9eb2-7183e1470c54.png)

**Comment by ChadABratton** [comment]
Issue can now be closed. Food banks testing is all done!

**Comment by abquirarte** [comment]
yay!
