### ISSUE TITLE
Review/add semantic HTML

### ISSUE THREAD

**Issue by lukefretwell** [cagov/Alpha#309]
Let's review and make sure we've properly incorporated semantic HTML into these into the templates, particularly:

* Header
* Nav
* Footer
* What else?

Would also be 💥 if we incorporated this into our accessibility rules.

Reference: https://www.w3schools.com/html/html5_semantic_elements.asp

cc @artuoma @aaronhans @carterm

**Comment by aaronhans** [comment]
Looks like @artuoma took care of this here https://github.com/cagov/Alpha/commit/746f44ef10e06c1ffdc94ba2838418a35a3f17cb#diff-002c23570599c09b58e74222987d8270

**Comment by abquirarte** [comment]
sweet, thanks!
