### ISSUE TITLE
Update website verification information

### ISSUE THREAD

**Issue by jpetrucione** [cagov/Alpha#315]
User story: As a user to CA.gov, I want verification/information that this is an official California State Government website.
 
Problem: Current header does not adequately convey that Alpha.ca.gov is an official CA state gov website

Solution: Update the current Bear Flag graphic + "State of California" copy to reflect what the US federal government does.
1 - Add copy that reads "An official State of California website"

**Comment by jpetrucione** [comment]
Per https://www.usds.gov/how-we-work

2) Add copy that when clicked on opens a dropdown 
2a) Copy: Here's how you know 

3) Add copy in dropdown: 
The .ca.gov means the website is a CA state website. The https/ means it's secure.

**Comment by lukefretwell** [comment]
@abquirarte can we add this to to-do. I can take lead on.

**Comment by abquirarte** [comment]
Yes!

**Comment by abquirarte** [comment]
Let's also add to 387!
