### ISSUE TITLE
End to end testing for all services

### ISSUE THREAD

**Issue by ChadABratton** [cagov/Alpha#319]
We need automated end to end testing for each service. 
We will check off the list as they are completed!

- [x] homepage 
- [x] min wage
- [x] food banks #302  
- [x] state holidays
- [x] licensed contractor
- [x] birth cert
- [x] calgrants
- [x] disability
- [x] spanish

**Comment by ChadABratton** [comment]
All end to end tests have now passed! We can close this story. 
![image](https://user-images.githubusercontent.com/28573666/73988735-66ae2700-48f8-11ea-86b8-1eb748c027dc.png)

![image](https://user-images.githubusercontent.com/28573666/73988799-a7a63b80-48f8-11ea-9bb7-a9ff889a0c73.png)

**Comment by abquirarte** [comment]
Glad it worked! Yay @ChadABratton . 

✅
