### ISSUE TITLE
Release Testing:  Find the minimum wage in your city

### ISSUE THREAD

**Issue by artuoma** [cagov/Alpha#333]
- [x] Page(s) integrated with correct folder name structure and metadata
- [x] Each english statement pasted into the translation spreadsheet and auto translated
- [x] Manual translation if applicable in translation spreadsheet
- [x] Automated end-to-end is created and run 
- [x] Automated accessibility test run using LightHouse with a score of 100
- [x] Manual accessibility checks performed ([See checklist](https://drive.google.com/open?id=0B72FqFUONAggazJwQURQeTBPMEZGRjJXSFNGcDJrMF9ENERR))
- [x] Mobile device testing for functionality and responsive design
- [x] Cross browser testing using devices and BrowserStack

**Specific issues identified (Functionality/Content/UX/UI)**
- [x] Accordion structure outdated, needs to be updated
- [x] In the tables within the accordions, the headers aren't matching up with the columns: rates and places. 

**Link to parent user story**
- https://github.com/cagov/Alpha/issues/303

**Link to staging URL**
- https://staging.alpha.technology.ca.gov/services/find-minimum-wage-your-city/

**Comments on above checklist and issues**
Additional comments

**Comment by artuoma** [comment]
@lukefretwell Please let me know if anything I missed.

**Comment by aaronhans** [comment]
- [ ] fix food banks on mobile
- [ ] fix holiday links on state holidays
- [ ] food banks text inside js is not translated into chinese

**Comment by KimberlyglennTSM** [comment]
Closed.
