### ISSUE TITLE
Release Testing: Apply for a Cal Grant

### ISSUE THREAD

**Issue by artuoma** [cagov/Alpha#334]
- [x] Page(s) integrated with correct folder name structure and metadata
- [x] Each english statement pasted into the translation spreadsheet and auto translated
- [x] Manual translation if applicable in translation spreadsheet
- [x] Automated end-to-end is created and run 
- [x] Automated accessibility test run using LightHouse with a score of 100
- [x] Manual accessibility checks performed ([See checklist](https://drive.google.com/open?id=0B72FqFUONAggazJwQURQeTBPMEZGRjJXSFNGcDJrMF9ENERR))

**Specific issues identified (Functionality/Content/UX/UI)**
- [x] There should be a one return space on landing page of Cal Grant, on expanded view of step 1, between CADAA and "If you've already submitted your FAFSA or CADAA, you can go to step two." 
- [x] Most of this page is hyperlinked (spanish): https://staging.alpha.technology.ca.gov/es/apply-for-cal-grant/finish/

**Link to parent user story**
- https://github.com/cagov/Alpha/issues/303

**Link to staging URL**
- https://staging.alpha.technology.ca.gov/apply-for-cal-grant/
- https://staging.alpha.technology.ca.gov/apply-for-cal-grant/step-1/
- https://staging.alpha.technology.ca.gov/apply-for-cal-grant/step-2/
- https://staging.alpha.technology.ca.gov/apply-for-cal-grant/finish/

**Comments on above checklist and issues**
Additional comments

**Comment by artuoma** [comment]
@lukefretwell Please let me know if anything I missed.

**Comment by abquirarte** [comment]
✅
