### ISSUE TITLE
Release testing: Find food banks near you 

### ISSUE THREAD

**Issue by humancenteredhuman** [cagov/Alpha#344]
- [x] "Showing food banks near 95818" result is no longer a headline
- [x] Map is miss-aligned in IE

**Comment by aaronhans** [comment]
- [ ] IE11 issue: retrieved food banks display goes over the map

**Comment by aaronhans** [comment]
https://github.com/cagov/Alpha/pull/349

**Comment by abquirarte** [comment]
This is now fixed
