### ISSUE TITLE
cache busting on static assets

### ISSUE THREAD

**Issue by aaronhans** [cagov/Alpha#36]
Integrate dynamic file naming for static assets like js and css which update often

this can be done along with other developer experience upgrades like adding watch process to rebuild automatically

**Comment by aaronhans** [comment]
- [ ] js files should be built with dynamic names and inserted into all html files dynamically
- [ ] css assets should be built into a single cacheable bundle
- [ ] css should be purged so all of bootstrap we don't use is eliminates
- [ ] js assets should only deliver polyfills to older browsers which require them

**Comment by KimberlyglennTSM** [comment]
reviewed and approved
