### ISSUE TITLE
More SEO language support

### ISSUE THREAD

**Issue by carterm** [cagov/Alpha#360]
We should include alternate language meta links in each page.

sample...
`<link rel="alternate" href="[other language page]" hreflang="es">`

Also,
Add alternate language pages to the sitemap

Also,
Change the Chinese language selector to show Chinese characters

reference here...https://neilpatel.com/blog/international-seo/

alter here...https://support.google.com/webmasters/answer/189077?hl=en

we can verify language support [here](https://www.google.com/webmasters/tools/i18n)

**Comment by carterm** [comment]
Lang code has been added to the build.  Next time we swap we can give it a few days and check the reports.

**Comment by abquirarte** [comment]
✅
