### ISSUE TITLE
apply www redirects to production

### ISSUE THREAD

**Issue by ChadABratton** [cagov/Alpha#369]
Apply settings to production according to the google doc:
https://docs.google.com/document/d/1YY5axKhi6r0_7fPJUXu6iw5BPSIOxmHR/edit

Alpha.ca.gov is not redirecting properly. 
We currently have two versions of each page, one with www. and one without www.

- [x] create listeners, rules, https settings, and health probes for www redirect
- [x] purge CDN
- [x] verify app service custom domain settings
- [x] Test if redirects from non www to www are working as intended

**Comment by ChadABratton** [comment]
All working! All requests to alpha.ca.gov will now redirect to www version.

**Comment by abquirarte** [comment]
YAY! @ChadABratton 👏
