### ISSUE TITLE
component library v0.1

### ISSUE THREAD

**Issue by aaronhans** [cagov/Alpha#38]
Create at least 3 components based on widgets we are already using in our current content:
- tiny ca.gov top bar
- jumbotron
- accordions
- autocomplete
- footer

Review how these look when integrated in storybook vs other ways of presenting a "design system"

**Comment by aaronhans** [comment]
Changing this story goal to: Rollout an initial documentation system that includes the bootstrap components we are using, has our own look and feel applied.

We've done an initial version of this based on the bootstrap documents with our own stylesheet applied on top and it includes full page examples of our content types as a new templates section

Will add additional tasks for specific component and content type refinement as our understanding of priorities matures

**Comment by KimberlyglennTSM** [comment]
Reviewed and Closed.
