### ISSUE TITLE
security tooling

### ISSUE THREAD

**Issue by aaronhans** [cagov/Alpha#388]
Evaluate security tools we should integrate into our production pipeline

**Comment by aaronhans** [comment]
- use tool to evaluate all installed packages for known vulnerabilities: npm audit (we currently have a couple low severity issues in a dev dependency, no issues with production dependencies)
![Screen Shot 2020-02-11 at 11 22 08 AM](https://user-images.githubusercontent.com/353360/74271499-dab64980-4cc1-11ea-904c-daae1a7a0633.png)

- review tools that evaluate javascript code for issues

related but not directly in security scope: we will implement https://prettier.io/ which will handle a lot of formatting issues automatically so we don't need to include those types of rules in a linter

**Comment by ChadABratton** [comment]
All fixed! 
https://github.com/cagov/Alpha/pull/407

**Comment by ChadABratton** [comment]
Started dynamic Veracode scan on alpha.ca.gov

**Comment by ChadABratton** [comment]
Veracode scan story: https://github.com/cagov/Alpha/issues/412

**Comment by abquirarte** [comment]
closing. new issue for Beta should be created for additional security considerations.
