### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by ChadABratton** [cagov/Alpha#4]
- [x] setup account
- [x] add permissions
- [x] add to website Done, https://github.com/cagov/Alpha/issues/5#issue-528949011
- [ ] Draft summary of what we do have access to DRI- @carterm 
- [x] Close out ask with departments we reached out to

**Comment by ChadABratton** [comment]
https://github.com/cagov/Alpha/issues/5#issue-528949011

**Comment by carterm** [comment]
@abquirarte Do we have everything we need from Google Analytics at this point?  May we close this issue?

**Comment by abquirarte** [comment]
yes! Let's close.
