### ISSUE TITLE
Fix North/South travel bug in Caltrans

### ISSUE THREAD

**Issue by aaronhans** [cagov/Alpha#408]
do not display irrelevant flow directional issues

**Comment by aaronhans** [comment]
traveling from sacramento to san diego displayed both I-5 North and I-5 South

- [ ] figure out why i-5 North is showing up and prevent it

I-5 North is returned as one of the steps from mapbox maybe because they are taking you to the middle of LA.

I added some logic to remove shorter steps from the directions list so they are no longer included

**Comment by abquirarte** [comment]
thank you @aaronhans ! 👍
