### ISSUE TITLE
Veracode Security Findings

### ISSUE THREAD

**Issue by ChadABratton** [cagov/Alpha#412]
Overview:

- [x] Perform a static and dynamic scan of alpha.ca.gov

Uploaded results from static and dynamic veracode scan to google drive security folder. 
https://drive.google.com/drive/u/0/folders/1pvel7esoI0MBEmZaLSwlDh0Vf0bR00Hl

We can address the findings in individual stories as needed.

**Comment by ChadABratton** [comment]
9 flaws fixed from Static Scan:
![image](https://user-images.githubusercontent.com/28573666/74490618-f6fee580-4e7d-11ea-942a-e1fb90054f58.png)

**Comment by abquirarte** [comment]
closing
