### ISSUE TITLE
code license review

### ISSUE THREAD

**Issue by aaronhans** [cagov/Alpha#421]
I added an open source license to the alpha repo choosing GPL based on comments in the code CA gov handbook: https://codecagov-playbook.readthedocs.io/en/latest/licensing/ but I think that was probably too demanding of potential users (It requires all users to open source everything they build). Successful projects today that want people to use them aren't copyleft anymore, the USWDS uses https://creativecommons.org/publicdomain/zero/1.0/ so I'd like to chat with the team about which license we should use on our repos and then apply that decision.

**Comment by abquirarte** [comment]
@lukefretwell see comment above. 

We should sidebar on this tomorrow.
