### ISSUE TITLE
Monitoring and alerting for Alpha.ca.gov

### ISSUE THREAD

**Issue by ChadABratton** [cagov/Alpha#43]
Enable monitoring and alerting for alpha.ca.gov 

- [x] create monitoring rules to check for http/https errors
- [x] if more than 5 errors over 5 minutes, trigger alert to alphateam@alpha.ca.gov

**Comment by ChadABratton** [comment]
![image](https://user-images.githubusercontent.com/28573666/70939712-a85bd900-1ffd-11ea-8adc-87b245fda15c.png)

**Comment by ChadABratton** [comment]
All done, issue pushed to review status.

**Comment by KimberlyglennTSM** [comment]
Reviewed the  issue log and ready for close
