### ISSUE TITLE
Accessibility bugs

### ISSUE THREAD

**Issue by aaronhans** [cagov/Alpha#432]
The following bugs were pointed out by the DOR representative:

~- [ ] blank table cells in min wage~ no blank cells, works properly in voiceover, nvda
- [x] min wage results do not automatically play after search: use aria-live="polite" everywhere we dynamically insert results into page
- [x] should dismiss the autocomplete options if form is submitted successfully without choosing one because screenreader describing the result list is unnecessary
- [x] inside both accordions and step list not automatically read after expansion
    need aria-expanded boolean on the trigger
    already have aria-hidden boolean on the hidden/showing section
    need to set focus on containing div
- [x] food banks phone numbers not linked
- [x] get directions are not links
- [x] get directions uses same text always: aria-label used

**Comment by lukefretwell** [comment]
@aaronhans I was getting ready to document some of this and realize I don't have to. 💪

**Comment by aaronhans** [comment]
that last one gets sorted out with the autoFirst option in awesomplete, setting that everywhere in latest lint fix updates

**Comment by aaronhans** [comment]
https://github.com/cagov/Alpha/pull/601
