### ISSUE TITLE
performance bugs

### ISSUE THREAD

**Issue by aaronhans** [cagov/Alpha#433]
- [ ] too much js on food banks
  (make sure no 3rd party js loads on mobile where we don't show the map)
- [ ] too much js on road closures
  (replace address lookup with azure endpoint)
- [x] too much js on water prototype
  (replace address lookup with azure endpoint)
- [x] need to keep ES6 module bundle as ES6, webpack is now transpiling it down top ES5, probably need to switch to rollup for this

**Comment by abquirarte** [comment]
is this still relevant @aaronhans ?

**Comment by aaronhans** [comment]
Thanks for following up @abquirarte Yes this is critical but it is going to take a few days to build our own location autocomplete service. Carter found some good azure services we can base it on but we need to architect it securely. I am hoping to address this along with other large projects like spiffing up the design system during the bridge time.
