### ISSUE TITLE
resolve 502 bad gateway on https://staging.alpha.technology.ca.gov

### ISSUE THREAD

**Issue by ChadABratton** [cagov/Alpha#44]
@carterm @aaronhans 
Do either of you know what has caused the 502 Bad Gateway? 
 https://staging.alpha.technology.ca.gov

Did either of you make changes last week? Just trying to get it working again and prepare for the DNS cutover for alpha.ca.gov

**Comment by aaronhans** [comment]
We figured out that the staging.alpha.ca.gov was messed up because github was deploying stuff outside of the public directory to the server. We don't want the domain with .technology. We verified that the staging server worked again when we put only stuff on the public server on it

**Comment by ChadABratton** [comment]
502 Bad gateway is resolved. Issue can be closed.

**Comment by KimberlyglennTSM** [comment]
Reviewed and closed.
