### ISSUE TITLE
Fix CI-CD Deployment Process

### ISSUE THREAD

**Issue by ChadABratton** [cagov/Alpha#47]
PR from any branch should NOT deploy to staging. It should be for specific branches such as "master" or "staging" only.

**Comment by ChadABratton** [comment]
This has been fixed. The Pull request is only deploying to staging after being approved in Github and merged into the master branch of the alpha repo. 

AzurePipelines.yml file:

`# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

# no PR triggers
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1`

**Comment by abquirarte** [comment]
thnx!
