### ISSUE TITLE
Release 3 End to end testing

### ISSUE THREAD

**Issue by ChadABratton** [cagov/Alpha#471]
In addition to the already written end to end tests, we need new tests for the following services:
Note: this description will be updated regularly with PR's and commit #'s to see the code for each end to end test. 
- [x] Local Emergency Alerts https://github.com/cagov/Alpha/pull/461/files
- [x] Contact Us cagov/Alpha#460
- [x] Lifeline - Apply Online
- [InProgress] Lifeline - Check if you can get a discounted phone service
- [x] Water Quality https://github.com/cagov/Alpha/pull/482
- [x] Find-Shelter https://github.com/cagov/Alpha/pull/507/files
- [x] Unemployment

**Comment by ChadABratton** [comment]
Local Alerts and Contact us end to end testing is complete. 
![image](https://user-images.githubusercontent.com/28573666/75280847-0c033f00-57c3-11ea-801e-e7a233df0002.png)

**Comment by abquirarte** [comment]
✅ closing!
