### ISSUE TITLE
Add "This is an experiment" Banner+ Feedback Mechanism to Hello Page

### ISSUE THREAD

**Issue by abquirarte** [cagov/Alpha#48]
- [x] Draft content (@hilaryhb @humancenteredhuman )
- [ ] Determine design (@lukefretwell , @artuoma )

Adding from prior issue:

****As a visitor/user of Alpha.CA.gov, I would like to have the option to submit feedback so I can share my ideas or issues I'm having while using Alpha.CA.gov.**

- [ ] create /feedback page
- [ ] add to footer / page template

**Comment by hilaryhb** [comment]
From uk.gov: Alpha: This is a new service – your feedback will help us to improve it.
![Screen Shot 2019-12-16 at 6 32 17 PM](https://user-images.githubusercontent.com/58703973/70959964-7c0e7f80-2032-11ea-8b1b-6530c9957494.png)

**Comment by lukefretwell** [comment]
@abquirarte how is this different than the band already at the bottom of the page?

**Comment by abquirarte** [comment]
this was only 4 days ago? 
Do we think the band in the bottom is enough @hilaryhb and @humancenteredhuman ?

**Comment by humancenteredhuman** [comment]
From Stacey: "I see there’s a banner on alpha.ca.gov but it might be worth making it more explicit that it’s an experimental alpha “please give your feedback” and making it more prominent so when it’s available for anyone to see they acknowledge that it’s for testing and content is not necessarily factually correct."

**Comment by humancenteredhuman** [comment]
Suggested copy for top banner that disappears on acceptance: 
"This is an experimental project and a work in progress.
[Button] OK"

As for [feedback collection](#41 ), what would we like to ask @hilaryhb? @artuoma and I thought it would work best on the bottom, after users have had a chance to digest the page. (And that way it wouldn't disappear with the top banner.)

I like the way the GOV.UK page doesn't make you click away to give a quick bit of yes/no feedback.

Bottom banner: 
"Was this page easy to understand? 
Yes       No

Your [feedback](url) will help us improve."

"Feedback" links to open-ended survey.

**Comment by humancenteredhuman** [comment]
From GOV.UK <img width="983" alt="Screen Shot 2019-12-30 at 9 49 04 AM" src="https://user-images.githubusercontent.com/55514272/71593630-b889b300-2ae9-11ea-8412-36878ccf8a90.png">

**Comment by lukefretwell** [comment]
I'd prefer to keep the bar design the way it is and modify the text. I also like the link so that people can learn more so either keep linking to that or link to handbook page that describes it in more detail. We should have something that explains it simply and shares how people can give feedback.

@humancenteredhuman see issue specifically for feedback (can you move your respective comments related to this there?): 

https://github.com/cagov/Alpha/issues/41

**Comment by abquirarte** [comment]
I closed 41 and moved Luke's checklist here. (first comment on the thread)

**Comment by abquirarte** [comment]
another example from Portland's beta site: https://beta.portland.gov/ 
☝️ @humancenteredhuman @hilaryhb @artuoma

**Comment by KimberlyglennTSM** [comment]
Breaking this up this issue for sprint 4.

**Comment by abquirarte** [comment]
👉  Now tracking this on #75
