### ISSUE TITLE
Add Google Analytics to Website - Alpha.CA.Gov

### ISSUE THREAD

**Issue by ChadABratton** [cagov/Alpha#5]
- [ ] Enable SSI on alpha.ca.gov

**Comment by carterm** [comment]
Yes I can do that.

**Comment by carterm** [comment]
I can add the code snippet to the HTML.  I don't see any files to edit currently.  Where is the hello world at?

**Comment by aaronhans** [comment]
I see reporting going through to the ca.gov analytics account, thanks @artuoma

**Comment by carterm** [comment]
Working on getting SSI support on HTML pages for this to work.

**Comment by carterm** [comment]
- [ ] Add html extension support for SSI

**Comment by carterm** [comment]
No longer need SSI support.  Implemented as a separate javascript file.../ssi/analytics.js.  Tested and confirmed.  Closing.
