### ISSUE TITLE
Alpha website review

### ISSUE THREAD

**Issue by lukefretwell** [cagov/Alpha#559]
Here are my notes from a pass on the site.

## General

* Table class different in different places (some with th dark, some just default)
* 'Show all' not consistently used (showing here: https://staging.alpha.technology.ca.gov/apply-for-disability-insurance-benefits/ but not here: https://staging.alpha.technology.ca.gov/apply-for-cal-grant/)
* Accordions/steps aren't subheaded, so the structure isn't great.
* On some steps pages, we say in the description 'steps to ...' but in others we simply describe the service.
* Internal content in the steps seem overdesigned. It's difficult to process what's important and what's not, what's the CTA. 
* Would implement a few of the rules (no empty <p>, no multiple <br> in a row, no <hr>, no <p> or <br> inside form tags). 
* Some pages still have col-md, should be col-lg.
* Spacing issues (see screenshots below).

## Apply for a Cal Grant (college financial aid)

https://staging.alpha.technology.ca.gov/apply-for-cal-grant/

* 'Who can get a Cal Grant' accordion seems randomly added. Also, on another page, we have 'who qualifies' information in the first step. This gets to the standardized subcontent info conversation we had.

## Find shelters near you

https://staging.alpha.technology.ca.gov/find-shelter/

* Would add as alert: This tool is a work in progress. We plan to add more shelters and check that these details are correct.
* I (below) structured correctly?

<img width="1314" alt="Screen Shot 2020-02-27 at 1 25 15 PM" src="https://user-images.githubusercontent.com/1569463/75728573-129b2600-5c9d-11ea-8013-b37b13288269.png">

## Request a birth certificate

https://staging.alpha.technology.ca.gov/request-birth-certificate/

* Would use subheading for: 'More about requesting a birth certificate.' (same content conversation around standardizing subcontent. This feels tacked on.)

## Sign up for local emergency alerts

https://staging.alpha.technology.ca.gov/sign-up-for-local-emergency-alerts/

* Remove 'card-body bg-light' div

## Apply for a discounted phone service

https://staging.alpha.technology.ca.gov/apply-discounted-phone-service/

* Structure on main page doesn't make sense.
* Should have only one interactive element on the page (yes/no https://staging.alpha.technology.ca.gov/who-can-get-discounted-phone-service/)
* This page has odd code that conflicts with design system and template: https://staging.alpha.technology.ca.gov/who-can-get-discounted-phone-service/no-not-sure/?programs=no

## Apply for unemployment insurance

https://staging.alpha.technology.ca.gov/apply-for-unemployment-insurance/

* General: Same h1 on multiple pages is not great accessibility practice.
* h1 and p.lead are in col-8 here but they're in col-12 everywhere else.
* Accordions here are causing a slight flickr: https://staging.alpha.technology.ca.gov/apply-for-unemployment-insurance/how-to-apply/#how
* When I click the CA.gov logo from here I get a 'page not found': https://staging.alpha.technology.ca.gov/apply-for-unemployment-insurance/update-us-every-two-weeks/#update

## Apply for disability insurance benefits

https://staging.alpha.technology.ca.gov/apply-for-disability-insurance-benefits/

* Should this have a 'Steps to ...' h2 (like others)?
* Plus 'show all' (like others)?
* Lot of unnecessary design elements in steps sections

## Check your tap water quality

https://staging.alpha.technology.ca.gov/check-your-tap-water-quality/?systemId=CA0110005

* see screenshots

## Find the minimum wage in your city

https://staging.alpha.technology.ca.gov/find-minimum-wage-your-city/

* column width is 10 (should be 8 or standard for that content type)
* 'More about the minimum wage.' seems tacked on
* Results heading not consistent (The minimum wage in Lafayette, CA is) (vs https://staging.alpha.technology.ca.gov/find-shelter/)

## Hire a licensed contractor for home improvements

https://staging.alpha.technology.ca.gov/hire-licensed-contractor-home-improvements/

* Why are we explaining this is steps below steps <h2> when we don't do elsewhere? ("Follow these suggested steps to make home improvements the safe way and protect your home and your money.")
* Content is in col-md-9

## Check lane closures for your trip

https://staging.alpha.technology.ca.gov/check-lane-closures/

* Results - 'Get' directions button is still a standard button (suggest removing per 'link out policy')
* Big spacing between form and results.

## Prepare for a wildfire

https://staging.alpha.technology.ca.gov/steps-to-prepare-for-wildfire/

* Looks like translation.

## Footer

* 'Contact Us' should be 'Contact us' (AP Style)

## Screenshots (related to spacing)

<img width="1332" alt="Screen Shot 2020-02-27 at 1 09 10 PM" src="https://user-images.githubusercontent.com/1569463/75728684-7e7d8e80-5c9d-11ea-96c8-324f5b112b08.png">
<img width="1293" alt="Screen Shot 2020-02-27 at 1 18 01 PM" src="https://user-images.githubusercontent.com/1569463/75728687-80475200-5c9d-11ea-9e5c-78356238ca0d.png">
<img width="1326" alt="Screen Shot 2020-02-27 at 1 18 41 PM" src="https://user-images.githubusercontent.com/1569463/75728693-82a9ac00-5c9d-11ea-84b0-319fb9e435e6.png">
<img width="1315" alt="Screen Shot 2020-02-27 at 1 22 05 PM" src="https://user-images.githubusercontent.com/1569463/75728694-83424280-5c9d-11ea-933e-e87bbd9b3d2b.png">
<img width="1310" alt="Screen Shot 2020-02-27 at 1 40 01 PM" src="https://user-images.githubusercontent.com/1569463/75728699-84736f80-5c9d-11ea-86e5-7b89ef197a7c.png">
<img width="1260" alt="Screen Shot 2020-02-27 at 1 44 05 PM" src="https://user-images.githubusercontent.com/1569463/75728705-85a49c80-5c9d-11ea-940d-1d4f64079681.png">

cc @abquirarte @hilaryhb @artuoma @aaronhans @humancenteredhuman

**Comment by abquirarte** [comment]
adding this to master list #387 Thanks for documenting!

**Comment by abquirarte** [comment]
@lukefretwell which part looks like translation in wildfire prepare?

**Comment by lukefretwell** [comment]
@abquirarte looks like that's no longer an issue.
