### ISSUE TITLE
Updates for the bridge or beta

### ISSUE THREAD

**Issue by humancenteredhuman** [cagov/Alpha#580]
- [ ] Beta: Working with departments to understand what letters look like when they arrive. When should we call out the name of a department vs. "we"? The departments will tend to want us to name them. We should just be aware of that bias and choose what's best for the user. 

Sarah mentioned that GOV.UK was able to use: "We will mail you a letter." When the letter had the same logo as the website, this worked well. 

- [ ] Updating the alert on Cal Grant to "March 2, 2021" 

- [ ] Updates to unemployment insurance based on feedback from EDD:
"If you're approved for UI, you'll have to sign up for CalJOBS (unless you hear otherwise from us). And you'll have to look for work once a week. You can do that by contacting an employer about a job through CalJOBS or any other way."

**Comment by aaronhans** [comment]
- [ ] apply-for-unemployment-insurance/
 On desktop when linking between sections page jumps when content is long enough for the anchor link to activate, stays at top when content is short. Can we prevent jumping by not using anchor links just on big screens. We do need them on mobile always

**Comment by aaronhans** [comment]
- [ ] on food banks results do not clear if you search for a valid area, then search for invalid area which is confusing

**Comment by aaronhans** [comment]
- [ ] build our own location autocomplete API
- [ ] use our new API for water, road conditions (will radically increase performance)
- [ ] use azure endpoint for directions too (this will allow moving most client side functionality to API)
- [ ] add CHP incident data and long term road closures to lane closures page

**Comment by abquirarte** [comment]
## **Beta Bridge:** [copied from Release 387]

- Official state website verification design language: https://github.com/cagov/Alpha/issues/315 @lukefretwell taking lead on this (Beta Bridge)
- Handbook Update
- Release 3 blog post [For Friday]
- Optimize performance https://github.com/cagov/Alpha/issues/433~ Bridge
- Missing documentation https://github.com/cagov/Alpha/issues/434~ Bridge
- Product feedback List: https://github.com/cagov/Alpha/issues/559 
- Print Friendly 
- Update survey feedback form 

### Cal Grant
- Update alert to March 2, 2021 [Bridge]

### Water
- Use better water system url source? https://www.acwa.com/about/directory/ Beta 
- Make sure we do point to water system (US EPA)~ Beta 
- Show Water System Consistently~ Beta  

### Unemployment Insurance
- Minor content updates based on feedback from EDD received 3/3/2020
