### ISSUE TITLE
Test featured snippet

### ISSUE THREAD

**Issue by lukefretwell** [cagov/Alpha#6]
When I search for steps to do a particular public service, I would see a snippet of the instructions directly in the search results.

* Example page: https://www.gov.uk/learn-to-drive-a-car
* Exampe Google search results: https://www.google.com/search?client=firefox-b-1-d&q=learn+to+drive+a+car+uk

## References

* [How Google’s featured snippets work](https://support.google.com/websearch/answer/9351707?p=featured_snippets&hl=en&visit_id=637104024297115288-1092384526&rd=1)
* [Create good titles and snippets in Search Results](https://support.google.com/webmasters/answer/35624)

cc @artuoma @ChadABratton @carterm

**Comment by artuoma** [comment]
This is mainly achieved leveraging metadata. We should definitely ensure that all content is using https://schema.org.
