### ISSUE TITLE
Create sample "Function as a Service" 

### ISSUE THREAD

**Issue by carterm** [cagov/Alpha#63]
Creating a working Function As A Service prototype will make sure we have data options should our alpha want access to anything other than static data.

Recommend we make an offering that returns state holidays as a JSON result, which could feed other services that return HTML or ICAL.

**Comment by abquirarte** [comment]
Interested to see how this would come in useful in more data heavy user stories like: road conditions or safe drinking water. 

Anything from data.ca.gov worth borrowing in our user stories?

**Comment by carterm** [comment]
Completed.

Next task, Create service for state holidays ical format.

**Comment by KimberlyglennTSM** [comment]
Reviewed and approved.
