### ISSUE TITLE
CI-CD Diagram v2, Code Promotion process (production deployment approval process)

### ISSUE THREAD

**Issue by ChadABratton** [cagov/Alpha#67]
CI-CD diagram needs another update to reflect desired pipeline changes. 

- [x] Remove browserstack testing after deployment to staging (this should be testing during dev)

**Comment by ChadABratton** [comment]
[AlphaCICD (2).pdf](https://github.com/cagov/Alpha/files/4060871/AlphaCICD.2.pdf)

**Comment by ChadABratton** [comment]
Attached most recent pipeline diagram. Story can be closed.

**Comment by KimberlyglennTSM** [comment]
Thank you! -Ang
