### ISSUE TITLE
Review accessibility tools, make recommendations

### ISSUE THREAD

**Issue by aaronhans** [cagov/Alpha#68]
We need accessibility tool standards being used by everyone on the team, our automated tools and documented in our handbook

Would like to come up with recommended toolset of accessibility tools to use in:
- CI pipeline
- code linter
- manual in browser review

Started gathering tool info and capabilities here: https://docs.google.com/spreadsheets/d/1QSDU4J48Rjopw5a5y46uONLx6LkxUTwCCRwazaaVhfI/edit#gid=0

**Comment by abquirarte** [comment]
From slack:

Aaron Hans  23 hours ago
did some tool reviewing, unfortunately the current ca.gov was a good candidate for finding issues in a11y audits, notes added to tool. I'd recommend starting with the following toolset initially
- Webhint for linter integrated into code editor
- Lighthouse for CI integration (We will also use lighthouse for CI integrated performance audits)
- axe chrome plugin for manual test runs against live site versions

**Comment by aaronhans** [comment]
Thanks for your help with this @abquirarte after reviewing the accessibility reports for some of our baseline pages and the user experience of the in browser version of webhint, lighthouse online, lighthouse in dev tools and wave. We have updated our recommendations:

- Use Lighthouse in dev tools to trigger an audit on page (There is a firefox extension as well)

Still sticking with lighthouse for CI
and webhint for in editor linking

**Comment by aaronhans** [comment]
<img width="1049" alt="Screen Shot 2020-01-03 at 12 31 47 PM" src="https://user-images.githubusercontent.com/353360/71747693-2ead5300-2e25-11ea-82c2-aacad11165ca.png">

**Comment by aaronhans** [comment]
We saw identical results from webhint and in browser dev tools lighthouse accessibility reports on multiple pages so going with the built in lighthouse tool. Wave missed some issues on the licensed contractor page. Wave is also one of the tools that is not open source so we are dropping that from the candidate list.

**Comment by abquirarte** [comment]
To access this, you can go to your browser (Chrome or Firefox)
Control + Shift + I to access Dev tools
