### ISSUE TITLE
Develop how best to serve up and manage news content type

### ISSUE THREAD

**Issue by lukefretwell** [cagov/Alpha#69]
**Is your feature request related to a problem? Please describe.**
We discussed ways to serve up blog/news content types.

**Describe the solution you'd like**
We can do static or using a lightweight content management system (a la Gatsby).

**Describe alternatives you've considered**
@aaronhans?

**Comment by aaronhans** [comment]
Gatsby is an example of the best way to approach this: use static site generation with document regeneration and publication triggered on content updates.

Gatsby falls short of our performance goals though. Even if you follow all their best practices and do react server side rendering gatsby delivers a ton of client side js to support client side rehydration which radically slows down time to interactive. An audit of the official gatsbyjs blog shows this issue, first contentful paint is not too bad but time to interactive is very slow.

Using a static site generator that doesn't include such a heavyweight client side framework will solve this problem, https://www.11ty.dev/ is a good example of static site generation that doesn't require client side framework delivery

**Comment by aaronhans** [comment]
<img width="733" alt="Screen Shot 2019-12-20 at 2 12 54 PM" src="https://user-images.githubusercontent.com/353360/71296170-88951f80-2333-11ea-8e54-059baf6d6d2c.png">
<img width="769" alt="Screen Shot 2019-12-20 at 2 12 37 PM" src="https://user-images.githubusercontent.com/353360/71296171-88951f80-2333-11ea-96df-498ea83d2081.png">

**Comment by aaronhans** [comment]
^ above graphics are audits of similarly sized posts from gatsbyjs' blog and an 11ty site

**Comment by abquirarte** [comment]
Closing per thread: https://github.com/cagov/cwds/issues/19#issuecomment-571787708
