### ISSUE TITLE
Migration for Alpha.Ca.Gov Production Server

### ISSUE THREAD

**Issue by ChadABratton** [cagov/Alpha#71]
Alpha.ca.gov is currently running on an app service with limited resources and no CDN. 
Task: Migrate to new app service, app gateway, and implement CDN

- [x] Determine requirements for DNS request
- [x] Submit DNS Request to point alpha.ca.gov to new CDN endpoint
- [x] Create new CDN endpoint and custom domain to point to App Gateway
- [x] Create new App gateway rules, listeners, http settings, and health probes to properly monitor and direct incoming traffic to alpha.ca.gov from the CDN
- [x] Upload cert/pfx to Azure Portal - Vault for alpha.ca.gov
- [x] Staging / Prod Swap process tested

**Comment by ChadABratton** [comment]
FYI
@aaronhans 
@carterm 

**Status update on Infrastructure:**

- We are currently using Azure App Service: AS-GO-ALPH-D-004 to host the Alpha.ca.gov site. This is working fine for now. 
- We do not have any slots assigned to D-004 above and we are looking to migrate over to a new app service: as-go-alph-diae-d-001 to host the alpha site so that we can take advantage of the slot swap process.
- The staging slot staging (as-go-alph-diae-d-001/staging) is working just fine, I don't see any issues. 
- I uploaded the pfx to the vault:KV-CDT-ALPH-D-001
- I am planning to request a DNS cutover soon, so that the DNS team can cutover from the old D-004 app service to the new prod app service.

**Comment by ChadABratton** [comment]
I spoke with CDT today, confirmed DNS request below:

1st A record:
www.test.alpha.ca.gov to IP 52.246.72.160

2nd A record:
test.alpha.ca.gov to IP 52.246.72.160

**Comment by ChadABratton** [comment]
Example of the HTTPS setting attached to health probe in Azure Cloud, this is required to enforce https and is used within the rules and listeners to properly direct traffic.
![image](https://user-images.githubusercontent.com/28573666/72096569-51c97e00-32cf-11ea-9c35-5b4998cd0468.png)

**Comment by ChadABratton** [comment]
All done! We can close the issue.

**Comment by abquirarte** [comment]
✅ yay!
