### ISSUE TITLE
Update homepage: Add sprint 1-2 user needs to live site: alpha.ca.gov

### ISSUE THREAD

**Issue by abquirarte** [cagov/Alpha#72]
We need to update our "homepage" to add the prototypes we have "shipped" and add to the "live" alpha.ca.gov site. 

This will require:

- [x] Update content type in design system [homepage](https://cwds.dev/docs/4.3/templates/home/#)
- [x] Document/create process to go from "shipped" to "live" and in production.  
- [x] User stories ready for posting: minimum wage, state holidays, birth certificate (someone please add the correct links)
- [x] Clean up prototypes 
- [x] Finalize #48 (this is an experiment and feedback)
- [x]  @jpetrucione to think through release Social media messaging

**Comment by abquirarte** [comment]
Art's link: https://cwds.dev/docs/4.3/templates/home/#

**Comment by lukefretwell** [comment]
@artuoma @abquirarte @aaronhans suggestions for MVP based on template:

* Remove search box
* Remove 'California Initiatives' and 'Find Services' section
* Change 'Popular services' heading to 'Popular'
* Remove nav links

**Comment by humancenteredhuman** [comment]
Prototypes: 
https://cagov.github.io/UX/state-holidays/v2
https://cagov.github.io/UX/mw/v6
https://cagov.github.io/UX/birth-certificate

**Comment by lukefretwell** [comment]
@artuoma @humancenteredhuman we need to review the ☝️ prototypes for consistency. There are a few issues related to structure and code. I'm not sure where we are in the process of moving these to a standard template and design system yet, but want to flag.

**Comment by aaronhans** [comment]
Here is a checklist for promoting a prototype from the UX repository to become part of the alpha site
- content team verifies version is ready to go live
- design team verifies that latest version conforms to style guide
- passes accessibility checks from lighthouse and axe
- code is transpiled to work in target browser set: [all evergreen browsers + IE11]
- page is reviewed on low end phones
- automated end to end tests are written and passed which verify major functionality 
- any included components have unit tests
- performance optimizations have been made in frontend code (slim dependency tree, concatenated, minified static assets, etc.)
- performance optimizations are in place on server (serve compressed files, use CDN, long cache headers + cache busting, etc.)
- performance and accessibility grades are recorded for posterity
- automated systems are in place to review performance and accessibility score regressions

**Comment by abquirarte** [comment]
@KimberlyglennTSM see Aaron's process above ☝️

**Comment by abquirarte** [comment]
https://cagov.github.io/UX/state-holidays/v2.html (FYI, need to update the upcoming holiday date @carterm )

**Comment by aaronhans** [comment]
The new homepage looks pretty lean contentwise, @jpetrucione had a good suggestion about adding some info about the Alpha project, looking forward to discussing what else we can include for this release. cc @artuoma 

![Screen Shot 2020-01-03 at 2 19 30 PM](https://user-images.githubusercontent.com/353360/71752499-2577b280-2e34-11ea-871a-1b968e79c670.png)

**Comment by jpetrucione** [comment]
With regard to info on the project, I was thinking we cld add a text box at the top, similar to what the PDX beta has. The goal being to contextualize the site for users and press. Our copy wld read something like: Thanks for visiting. Our goal with this site is to make your experience finding and using state services easier. It's a work in progress that will continue to expand and improve. We welcome your feedback.

**Comment by abquirarte** [comment]
From Slack: 
 I think we'll have a little more content than this
- up to 4 user needs
- survey/feedback for each user need 
- survey link content/feedback for the main site 
- perhaps move current hello CA content into an about page (coincides with JP's comment re: info)
- Expanded "this is an experiment" banner- _we need to make sure it's clear that this is an alpha, and we cannot guarantee 100% accuracy_
