### ISSUE TITLE
Make sure banner "this is an experiment" stands out in Release 1

### ISSUE THREAD

**Issue by KimberlyglennTSM** [cagov/Alpha#75]
Example from Portland's beta site: https://beta.portland.gov/ 

👉 **Prior issue** https://github.com/cagov/Alpha/issues/48

**Comment by aaronhans** [comment]
Is this a bootstrap component already @artuoma ? I think the dismiss makes it need to be javascript powered so I'd like to make a little web component for this unless there is already a css only version or super small javascript powered thing we can use

**Comment by artuoma** [comment]
@aaronhans I think we can use the Alerts module. https://cwds.dev/docs/4.3/components/alerts/ 
Do we have the JavaScript Library for it included?

**Comment by abquirarte** [comment]
sample from UK: https://design-system.service.gov.uk/components/phase-banner/

**Comment by abquirarte** [comment]
Australia example @hilaryhb and @artuoma @humancenteredhuman   https://www.gov.au/alpha/starting-a-business/questionnaire-activities.html

**Comment by carterm** [comment]
This needs to create a tracking cookie that expires after [1 day] which will prevent re-display.
