### ISSUE TITLE
enable CDN in production environment

### ISSUE THREAD

**Issue by aaronhans** [cagov/Alpha#79]
Use whatever CDN solution is easiest. I suspect there is an option available from azure configuration that is the easiest way to accomplish this

**Comment by KimberlyglennTSM** [comment]
Reviewed and closed

**Comment by ChadABratton** [comment]
**Issue**: www.alpha.ca.gov was not showing the correct site, it was showing old test.alpha site

**Fix**: We determined an issue in the CDN, the origin header was still pointing to the old test.alpha.ca.gov domain. We were able to update the origin header to point to alpha.ca.gov and then purge the CDN and waited a few minutes. All issues were resolved! Site is now online and working correctly from both alpha.ca.gov and www.alpha.ca.gov

**Comment by abquirarte** [comment]
> **Issue**: [www.alpha.ca.gov](http://www.alpha.ca.gov) was not showing the correct site, it was showing old test.alpha site
> 
> **Fix**: We determined an issue in the CDN, the origin header was still pointing to the old test.alpha.ca.gov domain. We were able to update the origin header to point to alpha.ca.gov and then purge the CDN and waited a few minutes. All issues were resolved! Site is now online and working correctly from both alpha.ca.gov and [www.alpha.ca.gov](http://www.alpha.ca.gov)

Re-opening until we finish documenting. Thank you @ChadABratton !

**Comment by ChadABratton** [comment]
Documenting the CDN process.
1. Created a CDN profile in Azure
2. Created CDN endpoint with custom domain alpha.ca.gov to point
3. Set CDN endpoint origin host header to alpha.ca.gov
3. DNS Record reuqested: www.alpha.ca.gov.       300     IN      CNAME   testalphacagov.azureedge.net

![image](https://user-images.githubusercontent.com/28573666/72374129-86b64600-36be-11ea-8a0a-b178abdd32d6.png)

**Comment by ChadABratton** [comment]
@abquirarte  All done, see documentation above.

**Comment by abquirarte** [comment]
sweet, thank you.

**Comment by abquirarte** [comment]
☑️
