### ISSUE TITLE
Establish product framing

### ISSUE THREAD

**Issue by lukefretwell** [cagov/Alpha#8]
* [Document](https://docs.google.com/document/d/1_yB9t608T-oIU3FO85NdHLqbnaIOx6ADJS6cPvPSzlE/edit?usp=sharing)

- [ ] Add to handbook

**Comment by lukefretwell** [comment]
@artuoma check this out.

**Comment by abquirarte** [comment]
Final draft ready to review: https://docs.google.com/document/d/1_yB9t608T-oIU3FO85NdHLqbnaIOx6ADJS6cPvPSzlE/edit#

**Comment by abquirarte** [comment]
@artuoma - have you seen it :) 

@jpetrucione ready to add to handbook

**Comment by abquirarte** [comment]
closing this. Add to handbook will be a new issue within handbook repo if not one there already. ✅
