### ISSUE TITLE
Design About page for Release 1

### ISSUE THREAD

**Issue by abquirarte** [cagov/Alpha#81]
**Objective:** We want an about page that can be accessed across the site so that people that want additional context on what we are doing, help build trust for the more active users. 

Related to #72 

[Document](https://docs.google.com/document/d/1sC8Q-cqgWNTQSzRKxcmKYhOCFV-DchZ2Xrk0QmT8roo/edit#)

Content:

**About us** 
We're a small but mighty team of public servants and outside experts in user research and design. Together, we're reimagining CA.gov with and for the people of California.

Our first step: Make CA.gov easier for Californians to use. We've been working to help you access the services and information you need since December 2019.
Follow our progress
We're sharing our insights on our blog and Twitter. Our work in progress will live on GitHub and this website, Alpha.CA.gov.

**Comment by abquirarte** [comment]
### https://cagov.github.io/Alpha/public/about/

**Comment by lukefretwell** [comment]
- [ ] remove 'About us' text (or make it an h2)
- [ ] extraneous paragraph at end of copy
