### ISSUE TITLE
User story prototype feedback

### ISSUE THREAD

**Issue by lukefretwell** [cagov/Alpha#82]
@artuoma @humancenteredhuman @abquirarte @hilaryhb @aaronhans feedback on the current user story prototypes.

## Birth certificate

Reference: https://alpha.ca.gov/services/request-birth-certificate/
- [x] Needs meta/page title
- [x] Visit a county office' + 'Mail a request' + 'Apply online' really should be h3 (or single table with headers - see below)
- [x]  Information should be in one table (otherwise you're just using the table for design purposes and not content)
- [x] No bold on table header (default to style) (Art) They are H2 now sow bold by default

## State holidays

Reference: https://alpha.ca.gov/services/state-california-employee-holidays/
- [x]  Both items bold in the 'Next holiday' is too much bold. Would make 'Monday, Martin Luther King Jr. Day' not bold.
- [x]  Would combine 'Monday' with 'January 20' since they're date related.
- [x]  The 'Add State holidays to your calendar (iCalendar subscription)' feature isn't platform agnostic. Would remove. If we keep, would put in context of all the holidays (like below 'Upcoming holidays' or it's own 'Subscribe' section with a button)
- [x] Accordians don't adhere to design system (really big)
- [x]  Structure under '2020 holidays,' '2021 holidays' and 'More details about holidays' isn't proper (no h2 and/or multiple h3 tags)
- [x]  2020/2021 holidays table doesn't display fully on mobile
- [ ]  Would make 'Additional holidays' text a  ul. (Art - Nothing to list, why do this?)
- [x]  'July 1, 2020, to June 30, 2021' text is confusing since it's outside the 2020 timeframe
- [x]  Page container markup needs cleaning. There's a container around the accordion and it's causing unnecessary horizontal spacing.

## Minimum wage

Reference: https://alpha.ca.gov/services/find-minimum-wage-your-city/
- [x]  Make form inline (ref: https://getbootstrap.com/docs/4.3/components/forms/#inline-forms)
- [x]  '*More about the minimum wage.' (and general info like this) should be in a consistent location (like at the bottom of the page as an 'out' or a separate 'More info' h2. Note we do it differently here: https://cagov.github.io/UX/birth-certificate/
- [x]  make 'col-md-8' 'col-md-12'

## General 

- [x] Accordion (add arrow or plus to the right to indicate there's more information - see what USWDS does here: https://designsystem.digital.gov/components/accordion/)
- [x]  Is the 'Official California State Government' banner mobile?
- [x] 'More' figure out a subcomponent and style for

## Feedback Survey

Reference: https://cagov.github.io/Alpha/public/feedback/
- [ ]

**Comment by humancenteredhuman** [comment]
Thanks for the feedback, @lukefretwell. I've: 

- added the missing meta description and meta title to birth certificates
- cleaned up the heading structure on State Holidays

I agree that January 20 and Monday should be on the same line, or at least that Monday shouldn't be on the same line as MLK day. How big/bold it is feels like a design decision, so I'll leave it to @artuoma to update.

As for the Additional holidays — 1 personal holiday and 1 holiday credit — unfortunately, it's an HR policy that those credits are collected through the fiscal year (July 1, 2021, to June 30, 2022) and not the calendar year. So it would be incorrect to say you collect them in the calendar year of 2021, for example. Wish it weren't so.

**Comment by humancenteredhuman** [comment]
https://cagov.github.io/Alpha/public/

- [  ] "State of Find food banks near you" > "Find food banks near you"
- [  ] "Share Feedback" > "Share feedback"

**Comment by lukefretwell** [comment]
@artuoma feedback on birth certificate (http://staging.alpha.technology.ca.gov/services/california-birth-certificate/):

- [ ] remove the 'container mt-5' and just put that info in a `<p>` below the list (let's connect with @humancenteredhuman to figure out a standard for 'More info.' @artuoma I'd try to refrain from adding containers inside the main content area for now.

**Comment by abquirarte** [comment]
✅ thank you @artuoma ! These all have been applied to the staging site yeah?

**Comment by abquirarte** [comment]
confirmed with Luke. We are good.
