### ISSUE TITLE
Create automated build in production pipeline

### ISSUE THREAD

**Issue by carterm** [cagov/Alpha#97]
We are having to check in "compiled" pages for deployment.  It makes it difficult to review changes with every page changing every time.

**Comment by carterm** [comment]
It is very difficult to tell what changed.  This commit has 42 files changes even though very little changed -> [view commit](https://github.com/cagov/Alpha/pull/90/commits/77938eb41b11775bfb052d51ad86f79724dc8ad9)

**Comment by carterm** [comment]
Completed.  Now changes are easy to identify, because the server automatically builds all the source files and deploys the final "compiled" filed.

[view small commit](https://github.com/cagov/Alpha/pull/96/commits/5981e80fbee8a40fe9ccad22d18b8414db0517cd)

**Comment by abquirarte** [comment]
✅ awesome
